# TCL File Generated by Component Editor 10.1
# Fri Dec 14 08:27:49 YEKT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ssd1963 "ssd1963" v1.0.33
# | null 2012.12.14.08:27:49
# | 
# | 
# | F:/work/avalon-ssd1963/de1-nios-my/ssd1963/hdl/ssd1963.v
# | 
# |    ./hdl/ssd1963.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module ssd1963
# | 
set_module_property NAME ssd1963
set_module_property VERSION 1.0.33
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Components"
set_module_property DISPLAY_NAME ssd1963
set_module_property TOP_LEVEL_HDL_FILE hdl/ssd1963.v
set_module_property TOP_LEVEL_HDL_MODULE ssd1963
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/ssd1963.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1
add_interface_port clk reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global
# | 
add_interface global conduit end

set_interface_property global ENABLED true

add_interface_port global cs_n export Output 1
add_interface_port global wr_n export Output 1
add_interface_port global rd_n export Output 1
add_interface_port global d export Bidir 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 256
set_interface_property avalon_slave holdTime 1
set_interface_property avalon_slave isMemoryDevice true
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 4
set_interface_property avalon_slave readWaitTime 4
set_interface_property avalon_slave setupTime 1
set_interface_property avalon_slave timingUnits Nanoseconds
set_interface_property avalon_slave writeWaitStates 4
set_interface_property avalon_slave writeWaitTime 4

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avalon_slave_address address Input 4
add_interface_port avalon_slave avalon_slave_readdata readdata Output 32
add_interface_port avalon_slave avalon_slave_writedata writedata Input 32
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_chipselect chipselect Input 1
add_interface_port avalon_slave avalon_slave_byteenable byteenable Input 4
# | 
# +-----------------------------------
