/*
 * data.cpp
 *
 *  Created on: 21.08.2014
 *      Author: user
 */



const char *data =
"<schema>\n"
"\t\t<units>\n"
"\t\t\t<unit id = \"mhz_ut\">\n"
"\t\t\t\t<unit multiplier = \"1000000\" name = \"МГц\" name_en = \"MHz\"/>\n"
"\t\t\t\t<unit multiplier = \"1000\" name = \"КГц\" name_en = \"KHz\"/>\n"
"\t\t\t\t<unit multiplier = \"1\" name = \"Гц\" name_en = \"Hz\"/>\n"
"\t\t\t</unit>\n"
"\t\t</units>\n"
"\t\t<types>\n"
"\t\t\t<type id = \"string\" type = \"base\"/>\n"
"\t\t\t<type id = \"float\" type = \"base\"/>\n"
"\t\t\t<type id = \"u8\" type = \"base\"/>\n"
"\t\t\t<type id = \"s8\" type = \"base\"/>\n"
"\t\t\t<type id = \"u16\" type = \"base\"/>\n"
"\t\t\t<type id = \"s16\" type = \"base\"/>\n"
"\t\t\t<type id = \"u32\" type = \"base\"/>\n"
"\t\t\t<type id = \"s32\" type = \"base\"/>\n"
"\t\t\t<type id = \"dme_sfx_t\" name = \"Суффикс DME\" name_en = \"DME suffix\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"X\" name = \"X\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"Y\" name = \"Y\" value = \"1\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"dme_t\" name = \"Параметры DME\" name_en = \"DME parameters\" type = \"complex\">\n"
"\t\t\t\t<parameter hi = \"128\" id = \"ch\" increment = \"1\" initial = \"127\" lo = \"-127\" name = \"Канал DME\" name_en = \"DME channel\" type = \"u8\" validator = \"range\" view = \"tbox\"/>\n"
"\t\t\t\t<parameter id = \"sfx\" initial = \"0\" name = \"Суффикс DME\" name_en = \"DME suffix\" type = \"dme_sfx_t\" view = \"cbox\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"measure_ctl_t\" name = \"Измерение\" name_en = \"Measurement\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"START\" name = \"Старт\" name_en = \"Start\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"STOP\" name = \"Стоп\" name_en = \"Stop\" value = \"1\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"on_off_t\" name = \"xxx\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"ON\" name = \"Вкл.\" name_en = \"ON\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"OFF\" name = \"Выкл.\" name_en = \"OFF\" value = \"1\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"output_mode_t\" name = \"Выход\" name_en = \"Output mode\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"ANT\" name = \"Антенна\" name_en = \"Antenna\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"ATTEN\" name = \"Аттен.\" name_en = \"Attenuator\" value = \"1\"/>\n"
"\t\t\t\t<enum id = \"CALIB\" name = \"Калибр.\" name_en = \"Calibration\" value = \"2\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"start_ctl_t\" name = \"Запуск\" name_en = \"Start control\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"HIP\" name = \"ХИП\" name_en = \"HIP\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"CALIB\" name = \"Пачка\" name_en = \"Packet\" value = \"1\"/>\n"
"\t\t\t\t<enum id = \"EXT\" name = \"Внеш\" name_en = \"Ext.\" value = \"2\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"mode_ctl_t\" name = \"Режим\" name_en = \"Mode\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"REQESTER\" name = \"Запросчик\" name_en = \"Requester\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"RESPONDER\" name = \"Ответчик\" name_en = \"Responder\" value = \"1\"/>\n"
"\t\t\t</type>\n"
"\t\t\t<type id = \"dsp_onoff_t\" name = \"Откл. дисплея\" name_en = \"Power save\" type = \"enum\">\n"
"\t\t\t\t<enum id = \"NO\" name = \"НЕТ\" name_en = \"NO\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"a1_MIN\" name = \"1 МИНУТА\" name_en = \"1 Minute\" value = \"0\"/>\n"
"\t\t\t\t<enum id = \"a5_MIN\" name = \"5 МИНУТ\" name_en = \"5 Minutes\" value = \"1\"/>\n"
"\t\t\t\t<enum id = \"a10_MIN\" name = \"10 МИНУТ\" name_en = \"10 Minutes\" value = \"2\"/>\n"
"\t\t\t</type>\n"
"\t\t</types>\n"
"\t\t<parameters>\n"
"\t\t\t<parameter id = \"dme\" name = \"Параметры DME\" name_en = \"DME Parameters\" type = \"dme_t\"/>\n"
"\t\t\t<parameter id = \"measure_ctl\" initial = \"0\" name = \"Измерение\" name_en = \"Measurement\" type = \"measure_ctl_t\" view = \"cbox\"/>\n"
"\t\t\t<parameter id = \"output_mode\" initial = \"0\" name = \"Выход\" name_en = \"Output mode\" type = \"output_mode_t\" view = \"cbox\"/>\n"
"\t\t\t<parameter hi = \"70.0\" id = \"out_level\" increment = \"0.1\" initial = \"69.3\" label = \"dBm\" lo = \"-70.0\" name = \"Уровень\" name_en = \"Level\" type = \"float\" validator = \"range\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"start_ctl\" initial = \"0\" name = \"Запуск\" name_en = \"Start control\" type = \"start_ctl_t\" view = \"cbox\"/>\n"
"\t\t\t<parameter id = \"req_period\" increment = \"1\" initial = \"1300\" label = \"пар\\с\" label_en = \"pairs\\sec\" name = \"Период запросов\" name_en = \"Request period\" type = \"u32\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"req_freq\" increment = \"0.1\" initial = \"1050.20\" label = \"Мгц\" label_en = \"MHz\" name = \"Частота запроса\" name_en = \"Request freq.\" type = \"float\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"req_span\" increment = \"0.1\" initial = \"12.0\" label = \"мкс\" label_en = \"mcs\" name = \"Кодовый интервал запроса\" name_en = \"Request span\" type = \"float\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"rsp_span\" increment = \"0.1\" initial = \"12.0\" label = \"мкс\" label_en = \"mcs\" name = \"Кодовый интервал ответа\" name_en = \"Response span\" type = \"float\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"mode_ctl\" initial = \"0\" name = \"Режим\" name_en = \"Mode\" type = \"mode_ctl_t\" view = \"cbox\"/>\n"
"\t\t\t<parameter id = \"brightness\" increment = \"10\" initial = \"100\" label = \"%\" name = \"Яркость\" name_en = \"Brightness\" type = \"u8\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"dsp_onoff\" initial = \"0\" name = \"Отключение дисплея\" name_en = \"Power save\" type = \"dsp_onoff_t\" view = \"cbox\"/>\n"
"\t\t\t<parameter id = \"header_freq\" increment = \"0.001\" initial = \"1.001\" label = \"ГГц\" label_en = \"GHz\" type = \"float\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"header_level\" increment = \"0.1\" initial = \"13.00\" label = \"dBm\" type = \"float\" view = \"tbox_label\"/>\n"
"\t\t\t<parameter id = \"rf_on\" initial = \"1\" name = \"RF\" type = \"on_off_t\"/>\n"
"\t\t\t<parameter id = \"mod_off\" initial = \"0\" name = \"MOD\" type = \"on_off_t\"/>\n"
"\t\t</parameters>\n"
"\t\t<colors>\n"
"\t\t\t<color hex = \"0xF9FFF4\" id = \"BK_WHITE\"/>\n"
"\t\t\t<color hex = \"0x679AB9\" id = \"BK_BLUE\"/>\n"
"\t\t\t<color hex = \"0x97A39F\" id = \"BK_GRAY\"/>\n"
"\t\t\t<color hex = \"0xE5E9F2\" id = \"FNT_WHITE\"/>\n"
"\t\t\t<color hex = \"0xAFBFCF\" id = \"SELECTED\"/>\n"
"\t\t\t<color hex = \"0x267F00\" id = \"CAPTURED\"/>\n"
"\t\t\t<color hex = \"0xFF0000\" id = \"INVALID\"/>\n"
"\t\t\t<color hex = \"0x000000\" id = \"BLACK\"/>\n"
"\t\t</colors>\n"
"\t\t<fonts>\n"
"\t\t\t<font default = \"true\" id = \"TTF\" name = \"ARIALN.TTF\"/>\n"
"\t\t\t<font id = \"TTF_BOLD\" name = \"ARIALNB.TTF\"/>\n"
"\t\t\t<font id = \"GLY\" name = \"glyphs.ttf\"/>\n"
"\t\t</fonts>\n"
"\t\t<font_sizes>\n"
"\t\t\t<font_size id = \"FS_8\" value = \"12\"/>\n"
"\t\t\t<font_size id = \"FS_15\" value = \"16\"/>\n"
"\t\t\t<font_size default = \"true\" id = \"FS_20\" value = \"21\"/>\n"
"\t\t\t<font_size id = \"FS_30\" value = \"30\"/>\n"
"\t\t</font_sizes>\n"
"\t\t<views>\n"
"\t\t\t<view controller = \"lab\" font = \"TTF\" font_size = \"FS_30\" id = \"lab\" predefined = \"lab\"/>\n"
"\t\t\t<view captured_color = \"CAPTURED\" controller = \"tbox\" decorator = \"background,3d\" default_color = \"BK_WHITE\" font_size = \"FS_30\" id = \"tbox\" invalid_color = \"INVALID\" min_width = \"100\" predefined = \"tbox\" selected_color = \"SELECTED\"/>\n"
"\t\t\t<view captured_color = \"CAPTURED\" controller = \"cbox\" decorator = \"background,3d,cbox\" default_color = \"BK_WHITE\" font_size = \"FS_30\" id = \"cbox\" predefined = \"cbox\" selected_color = \"SELECTED\"/>\n"
"\t\t\t<view controller = \"btn\" d3_inversed = \"true\" decorator = \"background,3d\" default_color = \"BK_WHITE\" id = \"btn\" layout = \"center\" padding = \"10\" predefined = \"btn\" selected_color = \"SELECTED\">\n"
"\t\t\t\t<view font_size = \"FS_20\" inherited = \"lab\"/>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"tbox_cbox\" layout = \"stack\" vertical = \"false\">\n"
"\t\t\t\t<view inherited = \"tbox\"/>\n"
"\t\t\t\t<view inherited = \"cbox\"/>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"tbox_label\" layout = \"stack\" vertical = \"false\">\n"
"\t\t\t\t<view inherited = \"tbox\"/>\n"
"\t\t\t\t<view inherited = \"lab\" text_source = \"label\"/>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"status_label\" layout = \"center\" propagate = \"parameter_path\">\n"
"\t\t\t\t<view box_color = \"BLACK\" decorator = \"background,box\" default_color = \"BK_WHITE\" layout = \"stretch\" padding = \"2\" propagate = \"parameter_path\">\n"
"\t\t\t\t\t<view layout = \"stack\" propagate = \"parameter_path\" vertical = \"false\">\n"
"\t\t\t\t\t\t<view font_size = \"FS_8\" inherited = \"lab\" text_source = \"name\"/>\n"
"\t\t\t\t\t\t<view dynamic_source = \"parameter_value\" font_size = \"FS_8\" inherited = \"lab\"/>\n"
"\t\t\t\t\t</view>\n"
"\t\t\t\t</view>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"dme\" layout = \"stack\" vertical = \"false\">\n"
"\t\t\t\t<view inherited = \"tbox\" parameter_path = \".ch\"/>\n"
"\t\t\t\t<view inherited = \"cbox\" parameter_path = \".sfx\"/>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"default_composite_template\" layout = \"stack\" vertical = \"true\"/>\n"
"\t\t\t<view decorator = \"background\" default_color = \"BK_GRAY\" id = \"root\" layout = \"stretch\" padding = \"5\">\n"
"\t\t\t\t<view layout = \"stack\" stretch = \"last\" vertical = \"true\">\n"
"\t\t\t\t\t<view layout = \"stack\" stretch = \"last\" vertical = \"false\">\n"
"\t\t\t\t\t\t<view controller = \"parameter_view\" layout = \"stretch\" parameter_path = \"header_freq\"/>\n"
"\t\t\t\t\t\t<view controller = \"parameter_view\" layout = \"stretch\" parameter_path = \"header_level\"/>\n"
"\t\t\t\t\t\t<view layout = \"right_bottom\" vertical = \"false\">\n"
"\t\t\t\t\t\t\t<view layout = \"stack\" vertical = \"false\">\n"
"\t\t\t\t\t\t\t\t<view inherited = \"status_label\" parameter_path = \"rf_on\" propagate = \"parameter_path\"/>\n"
"\t\t\t\t\t\t\t\t<view inherited = \"status_label\" parameter_path = \"mod_off\" propagate = \"parameter_path\"/>\n"
"\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t</view>\n"
"\t\t\t\t\t<view layout = \"stack\" stretch = \"last\" vertical = \"true\">\n"
"\t\t\t\t\t\t<view decorator = \"background\" default_color = \"BK_BLUE\" layout = \"stretch\">\n"
"\t\t\t\t\t\t\t<view font = \"TTF_BOLD\" font_color = \"FNT_WHITE\" font_size = \"FS_8\" inherited = \"lab\" listen = \"menu_name\" static_text = \"xxx\"/>\n"
"\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t<view predefined = \"scroll_window\">\n"
"\t\t\t\t\t\t\t<view controller = \"window_selector\" layout = \"stretch\" listen = \"menu_select\" name_event = \"menu_name\" padding = \"10\">\n"
"\t\t\t\t\t\t\t\t<view id = \"main\" layout = \"center\" name = \"Главное\" name_en = \"Main\">\n"
"\t\t\t\t\t\t\t\t\t<view bw = \"140\" height = \"80\" layout = \"stack\" preferred_item_size = \"false\" vertical = \"false\">\n"
"\t\t\t\t\t\t\t\t\t\t<view decorator = \"background\" default_color = \"BK_BLUE\" layout = \"center\">\n"
"\t\t\t\t\t\t\t\t\t\t\t<view arg0 = \"control\" event = \"menu_select\" inherited = \"btn\" propagate = \"static_text\" static_text = \"Управление\" static_text_en = \"Control\"/>\n"
"\t\t\t\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t\t\t\t\t<view decorator = \"background\" default_color = \"BK_BLUE\" layout = \"center\">\n"
"\t\t\t\t\t\t\t\t\t\t\t<view arg0 = \"parameters\" event = \"menu_select\" inherited = \"btn\" propagate = \"static_text\" static_text = \"Калибровка\" static_text_en = \"Calibration\"/>\n"
"\t\t\t\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t\t\t\t\t<view decorator = \"background\" default_color = \"BK_BLUE\" layout = \"center\">\n"
"\t\t\t\t\t\t\t\t\t\t\t<view arg0 = \"settings\" event = \"menu_select\" inherited = \"btn\" propagate = \"static_text\" static_text = \"Настройки\" static_text_en = \"Settings\"/>\n"
"\t\t\t\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t\t\t<view id = \"control\" inherited = \"menu_page_template\" menu_ref = \"main\" name = \"Управление\" name_en = \"Control\"/>\n"
"\t\t\t\t\t\t\t\t<view id = \"parameters\" inherited = \"menu_page_template\" menu_ref = \"parameters\" name = \"Калибровка\" name_en = \"Calibration\"/>\n"
"\t\t\t\t\t\t\t\t<view id = \"settings\" inherited = \"menu_page_template\" menu_ref = \"screen\" name = \"Настройки\" name_en = \"Settings\"/>\n"
"\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t</view>\n"
"\t\t\t\t</view>\n"
"\t\t\t</view>\n"
"\t\t\t<view controller = \"menu\" id = \"menu_page_template\" item_template_view = \"menu_item\" item_template_view_complex = \"menu_item_complex\" layout = \"stack\" vertical = \"true\"/>\n"
"\t\t\t<view id = \"popup_menu\" layout = \"center\">\n"
"\t\t\t\t<view d3_inversed = \"true\" decorator = \"background, 3d\" default_color = \"BK_GRAY\" height = \"200\" layout = \"stretch\" padding = \"5\" width = \"400\">\n"
"\t\t\t\t\t<view layout = \"stack\" stretch = \"1\" vertical = \"true\">\n"
"\t\t\t\t\t\t<view decorator = \"background\" default_color = \"BK_BLUE\" layout = \"stretch\">\n"
"\t\t\t\t\t\t\t<view font = \"TTF_BOLD\" font_color = \"FNT_WHITE\" font_size = \"FS_8\" inherited = \"lab\" listen = \"popup_menu_name\" static_text = \"xxx\"/>\n"
"\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t<view predefined = \"scroll_window\">\n"
"\t\t\t\t\t\t\t<view layout = \"stretch\" padding = \"10\">\n"
"\t\t\t\t\t\t\t\t<view controller = \"popup_menu\" inherited = \"menu_page_template\" name_event = \"popup_menu_name\"/>\n"
"\t\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t\t<view layout = \"center\">\n"
"\t\t\t\t\t\t\t<view close = \"true\" inherited = \"btn\" propagate = \"static_text\" static_text = \"Закрыть\" static_text_en = \"Close\"/>\n"
"\t\t\t\t\t\t</view>\n"
"\t\t\t\t\t</view>\n"
"\t\t\t\t</view>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"menu_item_complex\" layout = \"stack\" vertical = \"false\">\n"
"\t\t\t\t<view inherited = \"btn\" popup_view = \"popup_menu\" propagate = \"text_source\" text_source = \"name\"/>\n"
"\t\t\t</view>\n"
"\t\t\t<view id = \"menu_item\" layout = \"menu_item\" ratio = \"0.5\">\n"
"\t\t\t\t<view inherited = \"lab\" text_source = \"name\"/>\n"
"\t\t\t</view>\n"
"\t\t</views>\n"
"\t\t<menus>\n"
"\t\t\t<menu id = \"main\">\n"
"\t\t\t\t<parameter_ref id = \"measure_ctl\"/>\n"
"\t\t\t\t<parameter_ref id = \"dme\"/>\n"
"\t\t\t\t<parameter_ref id = \"output_mode\"/>\n"
"\t\t\t\t<parameter_ref id = \"out_level\"/>\n"
"\t\t\t\t<parameter_ref id = \"start_ctl\"/>\n"
"\t\t\t</menu>\n"
"\t\t\t<menu id = \"parameters\">\n"
"\t\t\t\t<parameter_ref id = \"req_period\"/>\n"
"\t\t\t\t<parameter_ref id = \"req_freq\"/>\n"
"\t\t\t\t<parameter_ref id = \"req_span\"/>\n"
"\t\t\t\t<parameter_ref id = \"rsp_span\"/>\n"
"\t\t\t\t<parameter_ref id = \"mode_ctl\"/>\n"
"\t\t\t\t<parameter_ref id = \"brightness\"/>\n"
"\t\t\t\t<parameter_ref id = \"dsp_onoff\"/>\n"
"\t\t\t</menu>\n"
"\t\t\t<menu id = \"screen\">\n"
"\t\t\t\t<parameter_ref id = \"brightness\"/>\n"
"\t\t\t\t<parameter_ref id = \"dsp_onoff\"/>\n"
"\t\t\t</menu>\n"
"\t\t</menus>\n"
"</schema>\n"
"";
